README.md
=> 💡 Docs: Readme 수정

src/App.jsx, src/pages/splashPage/Splash.jsx
가로 최소 360px 최대 1024px로 설정 반응형으로 만들기위해 viewport사용하기
=> ✨ Feat: APP모바일뷰 설정

src/pages/bloodPostPage/BloodPost.jsx, src/pages/bloodPostPage/Styled.jsx, src/pages/bloodPostPage/header/Header.jsx, src/router.jsx
=> ✨ Feat: 긴급헌혈페이지 추가

src/pages/reservationPage/Styled.jsx
💄Design : 필터 디자인 및 위치 조정
BloodReservation의 Styled.jsx 수정
=> 💄Design : 필터 디자인 및 위치 조정

src/App.jsx, src/pages/signupPage/SignUpPet.jsx, src/pages/signupPage/Styled.jsx
💄Feat : 회원가입 페이지 완료 버튼 디자인
🔥Feat : 회원가입 페이지 푸터 삭제
=> 💄Feat : 회원가입 페이지 완료 버튼 디자인

src/pages/bloodPostDetailPage/Styled.jsx, src/pages/bloodPostDetailPage/detailCard/DetailCard.jsx, src/pages/bloodPostPage/Styled.jsx, src/pages/bloodPostPage/header/Header.jsx, src/pages/splashPage/Splash.jsx
[Feat: 검색할때 엔터쳐도 검색되게 추가]
[Feat:스플래쉬페이지 서비스 제목변경]
[💄 Design: 상세페이지 댓글 하단고정]
=> 💄 Design: 상세페이지 댓글 하단고정

src/pages/reservationPage/Styled.jsx
💄Design : 헌열 예약 페이지 지역 필터 너비 수정
=> 💄Design : 헌열 예약 페이지 지역 필터 너비 수정

src/pages/signupPage/SignUp.jsx, src/pages/signupPage/SignUpPet.jsx, src/pages/signupPage/header/Header.jsx
✨ Feat : 회원가입 페이지 progress bar 구현 완료
=> ✨ Feat : 회원가입 페이지 progress bar 구현 완료 

src/pages/signupPage/SignUp.jsx, src/pages/signupPage/Styled.jsx
✨ Feat : 프로필 이미지 업로드 성공
✨ Feat : 프로필 이미지 변경 버튼 구현
💄 Design : 프로필 이미지 스타일 변경
=> ✨ Feat : 프로필 이미지 업로드 성공

src/pages/calendarPage/Styled.jsx
💄Design : 헌열 예약 상세페이지 다음 버튼 크기 조절
=> 💄Design : 헌열 예약 상세페이지 다음 버튼 크기 조절

src/components/myPageComponent/ProfileEdit.jsx, src/pages/myPage/MyPageEdit.jsx, src/pages/myPage/PetEdit.jsx, src/pages/myPage/PetRegister.jsx, src/pages/signupPage/Styled.jsx
=> 💄Design: 프로필 박스 수정

src/components/myPageComponent/PetInfoCard.jsx, src/components/myPageComponent/ProfileEdit.jsx, src/components/myPageComponent/ReservationCard.jsx, src/pages/myPage/Styled.jsx, src/pages/myPage/header/Header.jsx, src/pages/signupPage/SignUpPet.jsx, src/pages/signupPage/Styled.jsx, src/pages/signupPage/header/Header.jsx
헤더를 고정하고 기/디가 요청한 수정사항을 반영했습니당~
=> 💄Design: header 고정

src/pages/myPage/AccountManage.jsx, src/pages/myPage/MyPageMain.jsx, src/pages/myPage/header/Header2.jsx
=> ✨feat: Mypage 백버튼

src/pages/calendarPage/CalendarPage.jsx
=> 💄 Design : 캘린더 디자인 구현 완료

src/pages/mapPage/Map.jsx, src/pages/mapPage/Styled.jsx, src/router.jsx
디자인 살짝 남았고 지도 좀 더 만져야 하지만 1차 완료
=> ✨feat: 지도 페이지 1차 완료

src/pages/calendarPage/CalendarPage.jsx, src/pages/calendarPage/Styled.jsx
=> 🐛 Fix : 캘린더 페이지 콘솔 오류 해결

src/pages/calendarPage/Styled.jsx, src/pages/reservationPage/Styled.jsx
=> 💄 Design : 병원 사진 크기 fit 완료

src/assets/icons/pinkLine.svg, src/components/myPageComponent/ProfileEdit.jsx, src/pages/explainPage/Standard.jsx, src/pages/explainPage/Styled.jsx, src/pages/explainPage/header/Header.jsx, src/pages/mapPage/Styled.jsx, src/pages/myPage/Styled.jsx, src/pages/postWritePage/Styled.jsx, src/router.jsx
=> ✨feat: 헌혈 기준 페이지 1차 작업

src/pages/calendarPage/CalendarPage.jsx, src/pages/reservationPage/Styled.jsx
🐛 Fix : 캘린더 페이지 변수 수정 및 사진 fit
=> 🐛 Fix : 캘린더 페이지 변수 수정 및 사진 fit

src/pages/myPage/MyPageEdit.jsx
=> 🔥Fix: 강아지 정보 등록 페이지 수정

src/pages/calendarPage/CalendarPage.jsx, src/pages/calendarPage/header/Header.jsx
🐛 Fix : 캘린더 페이지 헤더 병원 이름 오류 해결
=> 🐛 Fix : 캘린더 페이지 헤더 병원 이름 오류 해결

src/pages/calendarPage/CalendarPage.jsx, src/pages/mapPage/Map.jsx
🐛 Fix : 캘린더 및 맵 페이지 기능 구현 오류 해결
🐛 Fix : 캘린더 페이지 POST 오류 해결 완료
✨ Feat : 맵 페이지에 캘린더 선택 날짜 및 시간 출력 완료
=> 🐛 Fix : 캘린더 및 맵 페이지 기능 구현 오류 해결

src/App.jsx, src/pages/calendarPage/CalendarPage.jsx, src/pages/testPage/TestSecond.jsx, src/router.jsx
✨ Feat : 테스트 페이지 2번째 완료
⚡️ Feat : 캘린더 POST 오전/오후 구분 추가
=> ✨ Feat : 테스트 페이지 2번째 완료 & 캘린더 POST 수정

src/components/myPageComponent/PetInfoCard.jsx, src/components/myPageComponent/ProfilePet.jsx, src/pages/myPage/PetEdit.jsx, src/pages/myPage/PetInfo.jsx, src/pages/myPage/PetRegister.jsx
=> ✨feat: 이미지 업로드 기능

src/App.jsx, src/assets/icons/test10.svg, src/assets/icons/test11.svg, src/assets/icons/test12.svg, src/assets/icons/test5.svg, src/assets/icons/test6.svg, src/assets/icons/test7.svg, src/assets/icons/test8.svg, src/assets/icons/test9.svg, src/pages/calendarPage/CalendarPage.jsx, src/pages/calendarPage/Styled.jsx, src/pages/testPage/TestFifth.jsx, src/pages/testPage/TestFourth.jsx, src/pages/testPage/TestSecond.jsx, src/pages/testPage/TestSixth.jsx, src/pages/testPage/TestThird.jsx, src/router.jsx
💄 Design : 테스트 페이지 디자인 완료 
🐛 FIx : 캘린더 오류 해결
=> ✨ Feat : 테스트 페이지 디자인 완료 및 캘린더 오류 해결

src/pages/mapPage/Map.jsx, src/pages/testPage/TestResult1.jsx, src/pages/testPage/TestSecond.jsx
=> 🐛 Fix : 오타 및 디자인 수정

src/pages/myPage/MyPageEdit.jsx, src/pages/myPage/PetEdit.jsx, src/pages/myPage/PetRegister.jsx
=> 🐛fix: 강아지 등록하기 부분 수정

src/components/myPageComponent/ReservationCard.jsx, src/pages/myPage/ReservationList.jsx, src/pages/myPage/Styled.jsx, src/pages/myPage/header/Header.jsx, src/pages/myPage/header/Header2.jsx, src/pages/testPage/TestSecond.jsx
=> 💄 Design : 마이페이지 헤더 초기 수정

src/pages/myPage/MyPageEdit.jsx, src/pages/myPage/Styled.jsx, src/pages/myPage/header/Header.jsx, src/pages/signupSplashPage/SignUpSplash.jsx
=> ⏪Comment: 주석 되돌리기

src/components/myPageComponent/ReservationCard.jsx
=> ✨ Feat : 헌혈 예약 내역 관리 사진 추가
